server:
  port: 8080

spring:
  application:
    name: audit-demo-service
  artemis:
    mode: native
    broker-url: "tcp://localhost:61616"
    user: artemis
    password: artemis

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

authz:
  http:
    enabled: true
    identity-url-template: "http://localhost:${server.port}/usersgroups-query-api/query/api/rest/usersgroups/users/logged-in-user/permissions"
    user-id-header: "CJSCPPUID"
    action-header: "CPP-ACTION"
    accept-header: "application/vnd.usersgroups.get-logged-in-user-permissions+json"
    drools-classpath-pattern: "classpath:/acl/**/*.drl"
    reload-on-each-request: true
    action-required: false
    deny-when-no-rules: true
    group-aliases:
      "Legal Advisers": "Legal Advisers"
      "Prosecuting Authority Access": "Prosecuting Authority Access"
    exclude-path-prefixes:
      - "/usersgroups-query-api/"
      - "/actuator"
      - "/error"

audit:
  http:
    enabled: true
  artemis:
    destination: jms.queue.audit
    delivery-mode: PERSISTENT
    priority: 4
    time-to-live-ms: 0

demo:
  audit:
    log-consumer: true


logging:
  level:
    uk.gov.moj.cpp.auditdemo.jms: DEBUG
    uk.gov.moj.cpp.audit.jms.ArtemisAuditPublisher: DEBUG